# Generated by Django 4.1.7 on 2023-03-12 21:00

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0003_expiringimage_delete_tempurl_alter_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiringimage',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 21, 0, 21, 612609, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='expiringimage',
            name='original_image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expiringimage', to='Files.image'),
        ),
        migrations.AlterField(
            model_name='expiringimage',
            name='time_delta',
            field=models.IntegerField(default=300, validators=[django.core.validators.MaxValueValidator(30000), django.core.validators.MinValueValidator(300)]),
        ),
    ]
