# Generated by Django 4.1.7 on 2023-03-13 16:25

import Files.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Files', '0004_alter_expiringimage_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the file. Must be unique.', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='expiringimage',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 13, 16, 25, 39, 702795, tzinfo=datetime.timezone.utc), help_text='Timestamp of creation.'),
        ),
        migrations.AlterField(
            model_name='expiringimage',
            name='file',
            field=models.ImageField(help_text='Representation of image in filesystem.', null=True, upload_to=Files.models.get_expiring_dir_path),
        ),
        migrations.AlterField(
            model_name='expiringimage',
            name='original_image',
            field=models.OneToOneField(help_text='Relation to original Image instance', on_delete=django.db.models.deletion.CASCADE, related_name='expiringimage', to='Files.image'),
        ),
        migrations.AlterField(
            model_name='expiringimage',
            name='time_delta',
            field=models.IntegerField(default=300, help_text='Time in seconds. After given time, instance will be deleted, handled by view.', validators=[django.core.validators.MaxValueValidator(30000), django.core.validators.MinValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(help_text='Representation of image in filesystem.', upload_to=Files.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.ForeignKey(help_text='User that created Image instance.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
