# Generated by Django 4.1.7 on 2023-03-13 16:38

import Files.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0006_image_height_image_width_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='height',
        ),
        migrations.RemoveField(
            model_name='image',
            name='width',
        ),
        migrations.AlterField(
            model_name='expiringimage',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 13, 16, 38, 21, 860060, tzinfo=datetime.timezone.utc), help_text='Timestamp of creation.'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(help_text='Representation of image in filesystem.', upload_to=Files.models.get_image_path),
        ),
    ]
